# fly.toml app configuration file generated for kohlrabii on 2025-04-23T18:57:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kohlrabii'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 3
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'performance'
  cpus = 1
