/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/fixtures/forecasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fixture Forecasts Query */
        get: operations["fixtures_get_fixture_forecasts_query"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FixtureForecastRead */
        FixtureForecastRead: {
            /** Home Win */
            home_win: number;
            /** Away Win */
            away_win: number;
            /** Home Clean Sheet */
            home_clean_sheet: number;
            /** Away Clean Sheet */
            away_clean_sheet: number;
            /** Home Goals For */
            home_goals_for: number;
            /** Away Goals For */
            away_goals_for: number;
            fixture: components["schemas"]["FixtureRead"];
        };
        /** FixtureForecastReadPagination */
        FixtureForecastReadPagination: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
            /** Items */
            items: components["schemas"]["FixtureForecastRead"][];
        };
        /** FixtureRead */
        FixtureRead: {
            /** Date */
            date: string | null;
            /** Gameweek */
            gameweek: number | null;
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
            /** Season */
            season: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    fixtures_get_fixture_forecasts_query: {
        parameters: {
            query?: {
                sort_by?: string | null;
                sort_desc?: boolean;
                page?: number;
                page_size?: number;
                season?: string | null;
                gameweek?: number | null;
                date?: string | null;
                team?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureForecastReadPagination"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
