"""remove badge_uri column from teams

Revision ID: 0f88f81db630
Revises: 4fc66645d3e5
Create Date: 2025-05-04 15:34:09.851579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f88f81db630'
down_revision: Union[str, None] = '4fc66645d3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'badge_uri')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('badge_uri', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
