"""add team relationship to fixtures

Revision ID: 4fc66645d3e5
Revises: 62d3f9a1dd21
Create Date: 2025-05-01 15:08:34.560599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc66645d3e5'
down_revision: Union[str, None] = '62d3f9a1dd21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixture', sa.Column('home_team_id', sa.Integer(), nullable=False))
    op.add_column('fixture', sa.Column('away_team_id', sa.Integer(), nullable=False))
    op.drop_constraint('uix_away_team_date', 'fixture', type_='unique')
    op.create_unique_constraint('uix_away_team_date', 'fixture', ['away_team_id', 'date'])
    op.drop_constraint('uix_home_team_date', 'fixture', type_='unique')
    op.create_unique_constraint('uix_home_team_date', 'fixture', ['home_team_id', 'date'])
    op.create_foreign_key(None, 'fixture', 'teams', ['away_team_id'], ['id'])
    op.create_foreign_key(None, 'fixture', 'teams', ['home_team_id'], ['id'])
    op.drop_column('fixture', 'home_team')
    op.drop_column('fixture', 'away_team')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixture', sa.Column('away_team', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('fixture', sa.Column('home_team', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fixture', type_='foreignkey')
    op.drop_constraint(None, 'fixture', type_='foreignkey')
    op.drop_constraint('uix_home_team_date', 'fixture', type_='unique')
    op.create_unique_constraint('uix_home_team_date', 'fixture', ['home_team', 'date'])
    op.drop_constraint('uix_away_team_date', 'fixture', type_='unique')
    op.create_unique_constraint('uix_away_team_date', 'fixture', ['away_team', 'date'])
    op.drop_column('fixture', 'away_team_id')
    op.drop_column('fixture', 'home_team_id')
    # ### end Alembic commands ###
