"""split base team and season_team tables

Revision ID: 62d3f9a1dd21
Revises: 70dce147d9f9
Create Date: 2025-05-01 12:46:22.065569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d3f9a1dd21'
down_revision: Union[str, None] = '70dce147d9f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_team_id', 'season', name='uix_team_season')
    )
    op.create_index(op.f('ix_season_teams_season'), 'season_teams', ['season'], unique=False)
    op.create_index(op.f('ix_fixture_gameweek'), 'fixture', ['gameweek'], unique=False)
    op.create_index(op.f('ix_fixture_season'), 'fixture', ['season'], unique=False)
    op.alter_column('fixture_forecasts', 'fixture_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_fixture_forecasts_fixture_id'), 'fixture_forecasts', ['fixture_id'], unique=False)
    op.alter_column('result', 'fixture_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_result_fixture_id'), 'result', ['fixture_id'], unique=False)
    op.add_column('teams', sa.Column('short_name', sa.String(length=100), nullable=False))
    op.add_column('teams', sa.Column('badge_uri', sa.String(length=512), nullable=False))
    op.drop_constraint('uix_tricode_season', 'teams', type_='unique')
    op.drop_column('teams', 'season')
    op.drop_column('teams', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('season', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.create_unique_constraint('uix_tricode_season', 'teams', ['tricode', 'season'])
    op.drop_column('teams', 'badge_uri')
    op.drop_column('teams', 'short_name')
    op.drop_index(op.f('ix_result_fixture_id'), table_name='result')
    op.alter_column('result', 'fixture_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_fixture_forecasts_fixture_id'), table_name='fixture_forecasts')
    op.alter_column('fixture_forecasts', 'fixture_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_fixture_season'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_gameweek'), table_name='fixture')
    op.drop_index(op.f('ix_season_teams_season'), table_name='season_teams')
    op.drop_table('season_teams')
    # ### end Alembic commands ###
