"""create fixture_forecasts

Revision ID: 70dce147d9f9
Revises: dbb9efe2c1f8
Create Date: 2025-04-03 15:34:20.966802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70dce147d9f9'
down_revision: Union[str, None] = 'dbb9efe2c1f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture_forecasts',
    sa.Column('forecast_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('home_win', sa.Float(), nullable=False),
    sa.Column('away_win', sa.Float(), nullable=False),
    sa.Column('home_clean_sheet', sa.Float(), nullable=False),
    sa.Column('away_clean_sheet', sa.Float(), nullable=False),
    sa.Column('home_goals_for', sa.Float(), nullable=False),
    sa.Column('away_goals_for', sa.Float(), nullable=False),
    sa.Column('home_attack', sa.Float(), nullable=False),
    sa.Column('away_attack', sa.Float(), nullable=False),
    sa.Column('home_defence', sa.Float(), nullable=False),
    sa.Column('away_defence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.fixture_id'], ),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixture_forecasts')
    # ### end Alembic commands ###
