"""Init migration

Revision ID: dbb9efe2c1f8
Revises:
Create Date: 2025-03-31 13:22:55.834021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb9efe2c1f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tricode', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('season', sa.String(length=4), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tricode', 'season', name='uix_tricode_season')
    )
    op.create_table('fixture',
    sa.Column('fixture_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('season', sa.String(length=100), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=True),
    sa.Column('home_team', sa.String(length=100), nullable=False),
    sa.Column('away_team', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('fixture_id'),
    sa.UniqueConstraint('away_team', 'date', name='uix_away_team_date'),
    sa.UniqueConstraint('home_team', 'date', name='uix_home_team_date')
    )
    op.create_table('result',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.fixture_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('fixture')
    op.drop_table('teams')
    # ### end Alembic commands ###
